#!/usr/bin/env bash
# this is a wrapper for parallelized execution of bats-exec-test
# it is intended to be run inside parallel's sempahore
# and redirects the necessary outputs to specific files

# $1 = test_output_dir, the rest is forwarded to bats-exec-test
test_output_dir="$1"
shift # all other parameters will be forwarded to bats-exec-test

mkdir -p "$test_output_dir"

# store the pid for waiting on finish
printf "%d" "$$" > "$test_output_dir/pid"

bats-exec-test "$@" 2>"$test_output_dir/stderr" >"$test_output_dir/stdout"

# store the result for marking end and retrieving errors
printf "%d" "$?" > "$test_output_dir/exitcode"