language: bash

os:
- linux

env:
  - BASHVER=
  - BASHVER=3.2
  - BASHVER=4.0
  - BASHVER=4.1
  - BASHVER=4.2
  - BASHVER=4.3
  - BASHVER=4.4
  - BASHVER=5

matrix:
  include:
    - os: osx

services:
  - docker

before_script:
 - |
   if [[ "${TRAVIS_OS_NAME:-}" == 'linux' ]]; then
     sudo apt-get install shellcheck
   fi

script:
- |
  if [[ "${TRAVIS_OS_NAME:-}" == 'linux' ]]; then
    # @todo: Remove "|| true" once all coding standards issues are fixed.
    ./shellcheck.sh
  fi

  if [[ "${TRAVIS_OS_NAME:-}" == 'linux' && -n "${BASHVER}" ]]; then
    docker build --build-arg bashver="${BASHVER}" --tag "bats/bats:bash-${BASHVER}" . &&
      docker run -it "bash:${BASHVER}" --version &&
      time docker run -it "bats/bats:bash-${BASHVER}" --tap /opt/bats/test
  else
    time bin/bats --tap test
  fi

notifications:
  email:
    on_success: never
