services:
    bats:
        build:
            context: "."
            dockerfile: "Dockerfile"
        networks:
            - "default"
        user: "root"
        volumes:
            - "./:/opt/bats"
networks:
    default:
