#!/usr/bin/env bash
# Usage: script/publish
#

set -euo pipefail
IFS=$'\n\t'

DRYRUN=
TAG="$(git describe --tags --exact-match)"
RELNOTES="$(git rev-parse --git-dir)/RELNOTES"

abort() {
  printf 'Aborting: %s\n' "$1" >&2
  exit 1
}

assert_release_notes() {
  test -s "$RELNOTES"
}

github_push() {
  git push --follow-tags ${DRYRUN:+--dry-run}
}

github_release() {
  local message
  printf -v message 'Bats %s\n\n%s' "${TAG#v}" "$(<"$RELNOTES")"

  hub release create --browse --message="$message" "$TAG"
}

npm_publish() {
  local publish=${DRYRUN:+pack}
  npm ${publish:-publish}
}

while getopts ':n' opt; do
  case $opt in
  # f) force=--force ;;
  n) DRYRUN=true; set -x ;;
  :) abort "Option -$OPTARG requires an argument." ;;
  \?) abort "Invalid option: -$OPTARG" ;;
  esac
done

assert_release_notes

github_push
github_release
npm_publish
