#!/usr/bin/env bash
set -e

trap "kill 0; exit 1" int

count=0
for filename in "$@"; do
  while IFS= read -r line; do
    if [[ "$line" =~ $BATS_TEST_PATTERN ]]; then
      let count+=1
    fi
  done <"$filename"
done

if [[ "$BATS_COUNT_ONLY" == 'true' ]]; then
  echo "$count"
  exit
fi

echo "1..$count"
status=0
offset=0
for filename in "$@"; do
  index=0
  {
    IFS= read -r # 1..n
    while IFS= read -r line; do
      case "$line" in
      "begin "* )
        let index+=1
        echo "${line/ $index / $(($offset + $index)) }"
        ;;
      "ok "* | "not ok "* )
        [[ "$BATS_PRETTY_FORMAT" == 'true' ]] || let index+=1
        echo "${line/ $index / $(($offset + $index)) }"
        [ "${line:0:6}" != "not ok" ] || status=1
        ;;
      * )
        echo "$line"
        ;;
      esac
    done
  } < <( bats-exec-test "$filename" )
  offset=$(($offset + $index))
done

exit "$status"
